- examples/hello-world-web/hello-world-web/wrapper.py
- requirements.txt
- surround/cli.py
- surround/runner/web/api.py
- surround/surround.py
- templates/new/main.py.txt
- templates/new/wrapper.py.txt
Fixes #76 
Fixes #81
Fixes #87 
Fixes #89 
- Check MIME type of JSON and Image
- Add support for video
> Minor Issues and Update Allowed Types

- surround/config.py
- templates/tutorial/main.py.txt
> Use models path to maintain consistency

- surround/remote/base.py
> Use yaml safe load while writing config

- templates/new/dodo.py.txt
> Remove the built docker image for a Surround project

- surround/cli.py
- surround/runner/web/api.py
- surround/surround.py
> Fix Internal logging

- surround/cli.py
- surround/runner/web/api.py
> Only provide upload endpoint for files

- surround/cli.py
- surround/tests/cli/project_cli/init_test.py
- surround/tests/cli/remote_cli/add_test.py
- surround/tests/cli/remote_cli/list_test.py
- surround/tests/cli/remote_cli/remote_test.py
> Remove validation check while creating projects

- surround/cli.py
- templates/new/config.yaml.txt
> Store wrapper-info in config

- surround/cli.py
- templates/new/.gitignore.txt
- templates/tutorial/.gitignore.txt
> Add .gitignore to the generated projects

- surround/tests/cli/project_cli/generated_project_test.py
- templates/new/dodo.py.txt
- templates/new/web_dodo.py.txt
Use commands:
- `surround run batchLocal`
- `surround run trainLocal`
- `surround run webLocal` (if web project)
> ENHANCE: Add tasks for running batch, train, and web locally

- templates/new/web_dodo.py.txt
> FIX: Expose ports in dev and prod tasks

- templates/new/dodo.py.txt
- templates/new/web_dodo.py.txt
- templates/new/web_runner.py.txt
> Revert "FIX: Ensure container is stopped when CTRL+C is used "

- surround/assembler.py
- surround/tests/surround_test.py
- templates/new/batch_runner.py.txt
> FIX: Stop pipeline on exception in filters and during init

- surround/tests/cli/project_cli/generated_project_test.py
- templates/new/dodo.py.txt
- templates/new/web_dodo.py.txt
First build an image using:
```
$ surround run build
```
Then start the image in interactive mode using:
```
$ surround run interactive
```
Then have fun :)
> ENHANCE: Start project docker image in interactive mode via run

- requirements.txt
- surround/visualise/visualise_classifier.py
Calculate classification metrics manually for the visualization tool
> FIX: Remove scikit-learn as a dependency

- .circleci/config.yml
> QUALITY: Remove unused dependencies from CI

- MANIFEST.in
- requirements.txt
- surround/experiment/drivers.py
- surround/experiment/experiment_reader.py
- surround/experiment/experiment_writer.py
- surround/experiment/gcloud_storage_driver.py
- surround/experiment/log_stream_handler.py
- surround/experiment/storage_driver.py
- surround/experiment/util.py
- surround/experiment/web/cli.py
- surround/experiment/web/edit_notes.py
- surround/experiment/web/experiment_app.py
- surround/experiment/web/experiment_explorer.html
- surround/experiment/web/experiment_explorer.js
- surround/experiment/web/experiment_explorer.py
- surround/experiment/web/getter_experiment.py
- surround/experiment/web/menu.html
- surround/experiment/web/project_explorer.py
- surround/experiment/web/view_logs.html
- surround/experiment/web/view_logs.py
- surround/tests/experiment_reader_test.py
- surround/tests/experiment_writer_test.py
- templates/new/dodo.py.txt
- templates/new/web_dodo.py.txt
To use this you must do the following:
- Create a project in the Google Cloud Platform Console
- Create a storage bucket 
- Create a Service Account, give it permissions to use storage buckets
- Download the JSON credentials file
- Put the credentials somewhere safe
- Create an environment variable `GOOGLE_APPLICATION_CREDENTIALS` with the value as the path to the JSON credentials file
- Run the command `surround config experiment.url gs://{bucket-name-here}/`
- Run `surround experimentation`
Depends on #187 & #199
> ENHANCE: Use Google Cloud Storage for experimentation storage

- surround/surround.py
- templates/new/batch_main.py.txt
- templates/new/dodo.py.txt
- templates/new/web_dodo.py.txt
- templates/new/web_main.py.txt
Also return state, runner and assembler as tuple from `surround.run` method
> QUALITY: Move experiment logic from generated project

- surround/experiment/web/experiment_explorer.html
- surround/experiment/web/experiment_explorer.py
Limits the number of experiments per page to 10
Depends on #201
> ENHANCE: Pagination for Experiment Explorer

- setup.py
- surround/checkers/surround_checker.py
- surround/linter.py
- templates/new/dodo.py.txt
- templates/new/web_dodo.py.txt
Surround Linter throws error when `print()` is used in the project
> ENHANCE: Add custom check for print statements

- README.md
> DOC: Update about and getting started link

- templates/new/batch_main.py.txt
- templates/new/dodo.py.txt
- templates/new/web_dodo.py.txt
- templates/new/web_main.py.txt
* Fix missing task description  
* Disable experimentation in new projects
Depends on #236
> Minor tweaks

- setup.py
- surround/CHANGELOG.md
> CONFIG: Add License to setup

- templates/new/web_runner.py.txt
> DOC: Print available endpoints info

- surround/config.py
- templates/new/init.py.txt
Add support for creating a versioned output folder for each run that stores the log files.
> NEW: Add setup function for logging handlers

- requirements.txt
- surround/checkers/surround_checker.py
- surround/experiment/util.py
- surround/project.py
- templates/new/.gitignore.txt
- templates/new/Dockerfile-compute-gpu.txt
- templates/new/Dockerfile-compute.txt
- templates/new/Dockerfile.txt
- templates/new/config.yaml.txt
- templates/new/dodo.py.txt
- templates/new/web_dodo.py.txt
Integrates Google Cloud AI Platform with the generated project, allowing the running of batch/training jobs in the cloud.
**TO TEST THIS PR**:
- Create a Google Cloud Platform account and project
- Enable the AI Platform Training & Prediction API, Google Cloud Storage JSON API, and Google Container Registry API.
- Create a service account for the project and download the JSON credentials file
- Ensure the service account has IAM permissions called `ML Engine Developer` & `Storage Admin`
- Set the environment var `GOOGLE_APPLICATION_CREDENTIALS` to the path to the JSON file
- Remove `surround==...` from both `requirements.txt` and `requirements-gpu.txt` in the generated project.
- In `Dockerfile` and `Dockerfile-gpu` add the following:
```
RUN git clone https://github.com/a2i2/surround.git …
```
> FEATURE: Cloud Compute with Google Cloud

- README.md
- examples/hello-world/main.py
This PR updates the simple example in the README.
> FIX: Hello world example in README

- surround_cli/requirements.txt
- surround_cli/surround_cli/cli.py
> ENHANCE: Upgrade tornado version required by surround cli

- .github/workflows/build.yml
- surround/pylintrc
- surround/tox.ini
- surround_cli/pylintrc
- surround_cli/requirements.txt
- surround_cli/tox.ini
- Add support for M1/M2 machines
> CONFIG: Update dependencies
